### PR TITLE
fix@package.json: add event-stream to "resolutions"

### PR DESCRIPTION
**Pull request by MarcBouchard**
Running "yarn" after cloning the repo throws error 'Request failed "404 Not Found"' on dependency "event-stream-3.3.6.tgz".

Adding the following to package.json file solves the issue:
```
"resolutions": {
  "**/event-stream": "^4.0.1"
}
```
[source](https://github.com/eclipse/che/issues/12077#issuecomment-443208053)

### CODE REVIEW

**Comment by MarcBouchard** [comment]
Really liking rambda so far 👌

**Comment by selfrefactor** [comment]
Much appreciated are your words and your PR.

**Comment by GrosSacASac** [comment]
it is because version 3.3.6 contained a vulnerability. Thanks for the temporary workaround, ideally we update npm-run-all

npm-run-all used ps-tree which uses event-stream
it was fixed in https://github.com/mysticatea/npm-run-all/releases/tag/v4.1.5

**Comment by GrosSacASac** [comment]
https://stackoverflow.com/questions/53578201/npm-err-404-not-found-event-stream3-3-6

**Comment by selfrefactor** [comment]
I am using recently https://renovatebot.com/ with Rambda and it has been good. I might apply it here as well, but meanwhile I will update to latest `npm-run-all` thanks to your detailed information about this issue.

**Pull request merged**
